language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-30.0.2
    - android-30
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

#optional, use it if only you haven't give permission yet.
#before_install:
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build