language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-31.0.2
    - android-30
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

#optional, use it if only you haven't give permission yet.
#before_install:
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-30"
script:
  #Remember to change gradle file to add this jacoco thing

  - ./gradlew clean build
  - ./gradlew test
  - ./gradlew jacocoTestReport
  - ./gradlew build check
 # - ./gradlew build jacocoTestReport assembleAndroidTest
  #- ./gradlew connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN='4ebb17a9-ca4d-43b5-8138-9c3fd5268c5b'