language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=25.0.0
    - CODECOV_TOKEN='8acf9189-8fc0-4683-b71c-ec0391cca266' #

android:
  components:
    - tools
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - build-tools-25.0.0
    - android-22
    - sys-img-armeabi-v7a-android-22

before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-28"

before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew assembleDebug
  - ./gradlew createDebugCoverageReport #
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"

after_success: #
  - bash <(curl -s https://codecov.io/bash) #